<a href="https://colab.research.google.com/github/gsostarko/PyTorch-Tutorial/blob/main/Intro_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch


## Definiranje tenzora

In [5]:
x = torch.empty(3)
print(x)

tensor([1.7024e-34, 0.0000e+00, 3.8097e-03])


In [7]:
x = torch.empty(3, 3)
print(x)

tensor([[3.8097e-03, 4.5660e-41, 3.8097e-03],
        [4.5660e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [10]:
x = torch.empty(3, 3, dtype=torch.int) #torch.int / torch.double / torch.float16
print(x.size()) # size() ispis dimenzije

torch.Size([3, 3])


In [11]:
x = torch.ones(2,2) # ispisuje matricu s jedinicama
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [12]:
x = torch.tensor([2.5, 0.1]) #stvaranje tenzora
print(x)

tensor([2.5000, 0.1000])


## Zbrajanje tenzora

In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(f"x= {x}")
print(f"y= {y}")

#jednostavne matematičke operacije
z = x + y
print(f"z= {z}")
#također moguće je zbrojiti sa
z = torch.add(x,y)
print(f"z= {z}")

x= tensor([[0.5239, 0.8416],
        [0.9144, 0.4705]])
y= tensor([[0.1291, 0.9857],
        [0.4016, 0.8382]])
z= tensor([[0.6530, 1.8273],
        [1.3160, 1.3087]])
z= tensor([[0.6530, 1.8273],
        [1.3160, 1.3087]])


## Oduzimanje tezora

In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(f"x= {x}")
print(f"y= {y}")


z = x - y
print(f"z= {z}")

z = torch.sub(x,y)
print(f"z= {z}")

x= tensor([[0.1807, 0.6992],
        [0.8556, 0.1399]])
y= tensor([[0.2526, 0.2962],
        [0.0629, 0.8676]])
z= tensor([[-0.0719,  0.4030],
        [ 0.7927, -0.7277]])
z= tensor([[-0.0719,  0.4030],
        [ 0.7927, -0.7277]])


## Multiplikacija tenzora

In [22]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(f"x= {x}")
print(f"y= {y}")


z = x * y
print(f"z= {z}")

z = torch.mul(x,y)
print(f"z= {z}")

x= tensor([[0.2917, 0.7700],
        [0.7492, 0.9764]])
y= tensor([[0.5598, 0.7257],
        [0.1022, 0.8180]])
z= tensor([[0.1633, 0.5588],
        [0.0765, 0.7987]])
z= tensor([[0.1633, 0.5588],
        [0.0765, 0.7987]])
