<a href="https://colab.research.google.com/github/gsostarko/PyTorch-Tutorial/blob/main/Intro_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch


In [5]:
x = torch.empty(3)
print(x)

tensor([1.7024e-34, 0.0000e+00, 3.8097e-03])


In [7]:
x = torch.empty(3, 3)
print(x)

tensor([[3.8097e-03, 4.5660e-41, 3.8097e-03],
        [4.5660e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [10]:
x = torch.empty(3, 3, dtype=torch.int) #torch.int / torch.double / torch.float16
print(x.size()) # size() ispis dimenzije

torch.Size([3, 3])


In [11]:
x = torch.ones(2,2) # ispisuje matricu s jedinicama
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [12]:
x = torch.tensor([2.5, 0.1]) #stvaranje tenzora
print(x)

tensor([2.5000, 0.1000])
